### ISSUE TITLE
Module jest-expo should have "jest-preset.js" or "jest-preset.json" file at the root.

### ISSUE THREAD

**Issue by mikecfisher** [gunnnnii/turbo-expo-trpc-starter#2]
Hi I've been trying to find a turborepo expo monorepo starter that has jest tests configured. This example is the closest I've found. In other apps when I import a react native component from the ui folder into a component in the apps/mobile folder I get all sorts of transpilation errors. 

I was trying to see if I could get it working in this repo but when I run `yarn test` I get this error. 

```
  Module jest-expo should have "jest-preset.js" or "jest-preset.json" file at the root.
```

This is off a fresh clone of this repo. Have you been able to get jest tests working in this manner?

**Comment by gunnnnii** [comment]
Hey, I never set up testing in this boilerplate so I imagine you need to add some config files to get that to work (probably shouldn't have this test script to begin with 😬).

I've personally never set up testing for Expo app before.. I'd expect everything to just work using jest and [react-native-testing-library](https://callstack.github.io/react-native-testing-library/), but you'd have to confirm on your own.
